title:              Dentistry
email:              samuels0052@hstat.org
description:        Freedom Project
author:             Samuel Sharivker
baseurl:            "/sep10-freedom-project/src/"
url:                "https://samuels0052.github.io"

# Social Profiles
twitter_username:
github_username: samuels0052
facebook_username:
instagram_username: live2cube
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
